# theme: jekyll-theme-merlot
theme: jekyll-theme-dinky
title: Big Fat Software, Inc. - Let's go big.
author: Big Fat Software, Inc.
description: > # this means to ignore newlines until "baseurl:"
  Big Fat Software, Inc. Let's learn to code, build something and ..Let's go big.
# social links
twitter_username: bigfatsoftware
github_username:  big-fat-software-inc